### ISSUE TITLE
Link from main page?

### ISSUE THREAD

**Issue by arpio23** [droidian-devices/devices.droidian.org#21]
Just wondering if it would make sense to have a link to the devices page from main droidian.org

If I wouldn't port a device, I would never end up on the subdomain.

**Comment by sanathusk** [comment]
@arpio23  I have already raised a [PR] (https://github.com/droidian-releng/droidian.org/pull/2/files) to add the link on main droidian website. Unfortunately it has noot been approved yet. @g7 Can you please have a look at the PR.

**Comment by FakeShell** [comment]
looks to be merged now
